#!/bin/bash
export EC2_HOME=/home/bitnami/ec2-api-tools-1.6.12.0
export AWS_ELB_HOME=/home/bitnami/ElasticLoadBalancing-1.0.23.0
export PATH=$PATH:$EC2_HOME/bin:$AWS_ELB_HOME/bin

#export JAVA_HOME=/usr

export AWS_ACCESS_KEY=AKIAJKESHIJ6FYLVN3CA
export AWS_SECRET_KEY=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
export EC2_PRIVATE_KEY=ovSIIdXi4jEATLBoysvUuL+zAYbhhHTSeI2zlvU0
export AWS_CREDENTIAL_FILE=/home/bitnami/credential-file-path